# Generated by Django 5.1 on 2024-11-26 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sended',
            field=models.ManyToManyField(related_name='sended', to=settings.AUTH_USER_MODEL),
        ),
    ]
